{% set name = "SINA" %}
{% set version = "1.5.0" %}
{% set sha256 = "3961381d11338fc424b45aedf675d6070060715fd18a5c75395efb93d40627e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: {{ sha256 }}
  url: https://github.com/epruesse/SINA/releases/download/v{{version}}/sina-{{version}}.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - arb-bio-devel
    - boost
    - zlib
    - tbb-devel
  run:
    - arb-bio-tools
    - boost

test:
  commands:
    - sina --help

about:
  home: https://github.com/epruesse/SINA
  license: GPLv3
  license_family: GPL
  summary: |
    SINA is a tool for aligning sequences with an existing multiple sequence
    alignment (MSA) at high accuracy. It can also execute a homology search based
    on the computed alignment and generate a per sequence classifications from the
    search results.
